<a href="https://colab.research.google.com/github/ELMehdiNaor/TensorFlow-Developer-Certificate-in-2022-Zero-to-Mastery/blob/main/00_TensorFlow_Fundamentals_Exerices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the necessary Packages: 
import tensorflow as tf 
print(tf.__version__)

2.8.0


#Exercise

🛠 00 TensorFlow Fundamentals Exercises:

* 1.Create a **vector**, **scalar**, **matrix** and **tensor** with values of your choosing using @tf.constant()

* 2.Find the **shape**, **rank** and **size** of the tensors you created in 1

* 3.Create two tensors containing random values between 0 and 1 with shape [5, 300]

* 4.Multiply the two tensors you created in 3 using **matrix multiplication**

* 5.Multiply the two tensors you created in 3 using **dot product**

* 6.Create a tensor with random values between 0 and 1 with shape [224,224,3]

* 7.Find the min and max values of the tensor you created in 6 along the first axis

* 8.Created a tensor with random values of shape [1, 224, 224, 3] then **squeeze it** to change the shape to [224, 224, 3]

* 9.Create a tensor with shape [10] using your own choice of values, then find then index which has the maximum value

* 10.**One-hot encode** the tensor you created in 9.

##1.Create a **vector**, **scalar**, **matrix** and **tensor** with values of your choosing using **@tf.constant()**

In [3]:
# Let's Create a vector: 
vector = tf.constant([5, 6, 7])
# Let's Create a scalar: 
scalar = tf.constant(10)
# Let's Create a Matrix: 
matrix = tf.constant([[7, 8], [9, 10]])
# Let's create a tensor: 
tensor = tf.constant([[[1, 2, 3],[4, 5, 6],[7, 8, 9]] , [[9, 8, 7],[6, 5, 4],[3, 2, 1]]])
# Display the end results: 
vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]], dtype=int32)>)

##2.Find the **shape**, **rank** and **size** of the tensors you created in 1

In [4]:
# Let's get some information from what we have just created in 1
# Getting information from a vector: 
print("Datatype of every element:", vector.dtype)
print("Number of dimensions(rank):", vector.ndim)
print("Shape of vector:", vector.shape)
print("Size of vector:", tf.size(vector))

Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 1
Shape of vector: (3,)
Size of vector: tf.Tensor(3, shape=(), dtype=int32)


In [5]:
# Getting information from a scalar: 
print("Datatype of every element:", scalar.dtype)
print("Number of dimensions(rank):", scalar.ndim)
print("Shape of scalar:", scalar.shape)
print("Total number of element in our scalar:", tf.size(scalar))

Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 0
Shape of scalar: ()
Total number of element in our scalar: tf.Tensor(1, shape=(), dtype=int32)


In [6]:
# Getting information from a matrix:
print("Datatype of every element:", matrix.dtype)
print("Number of dimensions(rank):", matrix.ndim)
print("Shape of Matrix:", matrix.shape)
print("Total number of elements in our matrix:", tf.size(matrix))

Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 2
Shape of Matrix: (2, 2)
Total number of elements in our matrix: tf.Tensor(4, shape=(), dtype=int32)


In [7]:
# Getting Information from a tensor:
print("Datatype of every element:", tensor.dtype)
print("Number of dimensions(rank):", tensor.ndim)
print("Shape of Tensor:", tensor.shape)
print("Total numbeeer of elements in our tensor:", tf.size(tensor))

Datatype of every element: <dtype: 'int32'>
Number of dimensions(rank): 3
Shape of Tensor: (2, 3, 3)
Total numbeeer of elements in our tensor: tf.Tensor(18, shape=(), dtype=int32)


##3.Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [9]:
# Let's set the seed first: 
tf.random.set_seed(42)
# Let's create two random tensors: 
random_tensor1 = tf.random.uniform(shape=(5,300)) 
random_tensor2 = tf.random.uniform(shape=(5,300))
# Display the tensors and there shape(just to make sure we created the right tensors):
random_tensor1, random_tensor2 

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [10]:
# Display the Shapes:
print("Shape of random_tensor1 is:", random_tensor1.shape)
print("Shape of random_tensor2 is:", random_tensor2.shape)

Shape of random_tensor1 is: (5, 300)
Shape of random_tensor2 is: (5, 300)


##4.Multiply the two tensors you created in 3 using **matrix multiplication**

In [11]:
# Matrix Multiplication of tensors we created in 3.:
# Shape before the matrix multiplication: 
print("Shape of random_tensor1:", random_tensor1.shape)
print("Shape of random_tensor2:", random_tensor2.shape)

Shape of random_tensor1: (5, 300)
Shape of random_tensor2: (5, 300)


In [12]:
# Before performing the matrix multiplication we need to do a little trick
# Let's transpose one of the two tensors first: 
random_tensor1_transposed=tf.transpose(random_tensor1)
print("Shape of the transposed tensor:", random_tensor1_transposed)

Shape of the transposed tensor: tf.Tensor(
[[0.6645621  0.532024   0.08404207 0.7396945  0.15861344]
 [0.44100678 0.29129946 0.03614604 0.6653172  0.12024033]
 [0.3528825  0.10571766 0.97732127 0.0787828  0.27218235]
 ...
 [0.31410468 0.54052293 0.21516645 0.7117733  0.8824879 ]
 [0.7593535  0.31425726 0.9786098  0.07013571 0.1432488 ]
 [0.03699052 0.2200619  0.00726748 0.9409125  0.44135118]], shape=(300, 5), dtype=float32)


In [17]:
# Let's perform matrix multiplication: 
res = tf.matmul(random_tensor1_transposed, random_tensor2) # Tensorflow can't display a [300x300] Matrix
print("The Shape of the resultant matrix  is:", res.shape)

The Shape of the resultant matrix  is: (300, 300)


##5.Multiply the two tensors you created in 3 using the **dot product**

In [18]:
# We will proceed the same way as we did in 4 but this time we will transpose the second random tensor
# First let's transpose the second random tensor:
transposed_random_tensor2 = tf.transpose(random_tensor2)
# Display the shape after transposing:
print("The Shape before transposing was:", random_tensor2.shape)

The Shape before transposing was: (5, 300)


In [19]:
# After transposing it became: 
print("The actual shape is:", transposed_random_tensor2.shape)

The actual shape is: (300, 5)


In [23]:
# Let*s perform the dot product and show the shape of the resultant tensor:
res_dot = tf.tensordot(random_tensor1, transposed_random_tensor2, axes=1)
res_dot

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

In [24]:
# Display the shape of the resultant: 
print("The shape of the resultant is:", res_dot.shape)

The shape of the resultant is: (5, 5)


##6.Create a tensor with random values between 0 and 1 with shape [224,224,3]

In [26]:
# Let's create our third random tensor: 
random_tensor3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval = 1)
random_tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

##7.Find the **min** and **max values** of the tensor you created in 6

In [28]:
# Let's find the minimum:
min_val = tf.reduce_min(random_tensor3)
# Display the minimum: 
print("The minimum value is:", min_val)

The minimum value is: tf.Tensor(2.3841858e-07, shape=(), dtype=float32)


In [29]:
# Let's find the maximum: 
max_val = tf.reduce_max(random_tensor3)
# Display the maximum:
print("The maximum value is:", max_val)

The maximum value is: tf.Tensor(0.9999918, shape=(), dtype=float32)


##8.Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [35]:
# Let's first create another tensor with random values:
random_tensor4 = tf.constant(tf.random.uniform(shape=(1, 224, 224, 3)))
random_tensor4
# The Shape of the tensor before squeezing: 
print("The shape before squeezing:", random_tensor4.shape)

The shape before squeezing: (1, 224, 224, 3)


In [37]:
# Let's squeeze the tensor first: 
squeezed_random_tensor4 = tf.squeeze(random_tensor4)
# The Shape of the tensor agter squeezing: 
print("The shape after squeezing:", squeezed_random_tensor4.shape)

The shape after squeezing: (224, 224, 3)


##9.Create a tensor with shape [10] using your own choice of values, then find **the index** which has **the maximum value**.

In [39]:
# Let's create a random tensor of shape [10]: 
random_tensor5 = tf.constant([100, 99, 98, 50, 1000, 2.75, 0.001, 999, 0, 1])

In [41]:
# Index our largest value: 
max_val_ind = tf.argmax(random_tensor5) 
# Display the index: 
print("The index is:", max_val_ind)

The index is: tf.Tensor(4, shape=(), dtype=int64)


In [42]:
# The max value of tensor is: 
print("The maximum value is:", tf.reduce_max(random_tensor5))

The maximum value is: tf.Tensor(1000.0, shape=(), dtype=float32)


##10.One-hot encode the tensor your created in 9.

In [45]:
# One-hot encoding the tensor we created in 9: 
tf.one_hot(tf.cast(random_tensor5, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>