<a href="https://colab.research.google.com/github/ELMehdiNaor/TensorFlow-Developer-Certificate-in-2022-Zero-to-Mastery/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensors using Tensorflow 
More specifically, we are going to cover: 
* Introduction to tensors 
* Getting information from tensors 
* Manipulating tensors 
* Tensors & NumPy
* Using @tf.function(a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

## Introduction to Tensors

In [49]:
# Import Tensorflow 
import tensorflow as tf 
print(tf.__version__)

2.8.0


In [50]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [51]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [52]:
# Create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [53]:
# Check the dimension of our vector 
vector.ndim

1

In [54]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [55]:
matrix.ndim

2

In [56]:
# Create another matrix 
an_matrix = tf.constant([[10., 7.], 
                         [3., 2.], 
                         [7., 10.]], dtype=tf.float16) # specify the data type with the dtype parameter
an_matrix         

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 7., 10.]], dtype=float16)>

In [57]:
# What is the number of dimensions of an_matrix?
an_matrix.ndim

2

In [58]:
# Let's create a tensor 
tensor = tf.constant([[[1, 2, 3], 
                     [4, 5, 6]],
                     [[7, 8, 9], 
                     [10, 11, 12]], 
                     [[13, 14, 15], 
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# What we have created so far: 
* Scalar: is a single number 
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number)

### Creating tensors with `tf.variable` 


In [59]:
import tensorflow as tf

# Let's Create the same tensor with tf.Variable() as above 
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
# Display the values of the tensors: 
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [60]:
# Let's try to change one of the elements in our changeable tensor: 
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
# How about we try.assign():
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try to change our unchangeable tensor: 
unchangeable_tensor[0] = 7
unchangeable_tensor

In [ ]:
# Let's try again using the .assign() method:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

🔑 **Note:** Rarely in pratice will you need to decide whether to use `tf.constant()` or `tf.variable()` to create tensors, as Tensorflow does this for you.
 However if in doubt, use `tf.constant()` and change it later if needed.

### Creating random tensors 

Random tensors are tensors of some arbitrary size which contain random numbers 

In [ ]:
 # Let's create two random (but the same) tensors: 
 # First random tensor:
 random_tensor1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
 random_tensor1 = random_tensor1.normal(shape=(3, 2))
 random_tensor1 

In [ ]:
 # Second random tensor: 
 random_tensor2 = tf.random.Generator.from_seed(42)
 random_tensor2 = random_tensor2.normal(shape=(3, 2))
 random_tensor2

In [ ]:
# Are the tensors equal? 
random_tensor1, random_tensor2, random_tensor1 == random_tensor2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (This is valuable when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[1, 2], 
                            [3, 4],
                            [5, 6]]) 
# Display the dimension of the tensor: 
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
# Let's shuffle our non-shuffled tensor for the first time: 
tf.random.shuffle(not_shuffled)

In [ ]:
# Let's shuffle for a second time: 
tf.random.shuffle(not_shuffled)

In [ ]:
# Let's shuffle for a third time: 
tf.random.shuffle(not_shuffled)

In [ ]:
# Let's shuffle for a fourth time: 
tf.random.shuffle(not_shuffled)

In [ ]:
# Let's shuffle for the fifth time: 
tf.random.shuffle(not_shuffled)

In [ ]:
 # Let's shuffle our tensor after setting the seed parameter: 
 tf.random.set_seed(42)
 tf.random.shuffle(not_shuffled, seed = 42)

In [ ]:
# Let's shuffle the tensor for the 2nd time after setting the seed parameter: 
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

🛠 **Exercise:** Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed, and pratice 
5 random tensors and shuffle them

### Let's do some exercise

In [ ]:
# Let's generate the first unshuffled tensor: 
not_shuffled1 = tf.constant([[5, 6],
                            [3, 4], 
                            [1, 2]])
# Shuffle Time !  
# First Shuffle :
tf.random.shuffle(not_shuffled)

In [ ]:
# Second Shuffle: 
tf.random.shuffle(not_shuffled1)

In [ ]:
# Third Shuufle: 
tf.random.shuffle(not_shuffled1)

In [ ]:
# Let's shuffle the tensor after setting the seed parameter:
# First Time:
tf.random.set_seed(15)
tf.random.shuffle(not_shuffled1, seed=15)

In [ ]:
# Second Time: 
tf.random.set_seed(15)
tf.random.shuffle(not_shuffled1, seed=15)

In [ ]:
# Third Time: 
tf.random.set_seed(15)
tf.random.shuffle(not_shuffled1, seed=15)

In [ ]:
# Let's generate a second unshuffled tensor: 
not_shuffled2 = tf.constant([[8, 9], 
                             [6, 7], 
                             [4, 5]])
not_shuffled2

In [ ]:
# Let's Shuffle the tensor: 
# 1st Shuffle: 
tf.random.shuffle(not_shuffled2)

In [ ]:
#  2nd Shuffle: 
tf.random.shuffle(not_shuffled2)

In [ ]:
# 3rd Shuffle: 
tf.random.shuffle(not_shuffled2)

In [ ]:
# Let's shuffle the second tensor after setting the seed parameter:
tf.random.set_seed(44)
tf.random.shuffle(not_shuffled2,seed=44)

In [ ]:
import tensorflow as tf


In [ ]:
not_shuffled4 = tf.constant([[9, 10], 
                             [7, 8],
                             [5, 6]])
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled4, seed=42) # operation level random seed

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones:
tf.ones([4,6])

In [ ]:
# Let's create a tensor of all zeros:
tf.zeros([4,6])

In [ ]:
# Let's create a second tensor of all zeros:
tf.zeros(shape=(4,4))

### Turn Numpy arrays into tensors 
The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on a GPU
(much faster for numerical computing)

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np 
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A 

In [ ]:
# Let's turn a numpy array into a tensorflow tensor: 
A = tf.constant(numpy_A)
A
A.ndim

In [ ]:
# Let's make it a 3-D tensor
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or dimension
* Size



In [ ]:
# Let's Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
  # Let's display some information about the tensor: 
  # Shape, Dimension and Size: 
  rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Let's display some various attributes of our tensor:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:",  rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

### Indexing tensors 
Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension: 
first_2_elements = rank_4_tensor[:2, :2, :2, :2]
first_2_elements

In [ ]:
# Get the first element from each dimension from each index except for the final one:
first_element = rank_4_tensor[:1,:1,:1,]
first_element

In [ ]:
# Let's create a rank 2  tensor (2 dimensions)
rank_2_tensor = tf.constant([[9, 10], 
                             [7, 8]])
rank_2_tensor


In [ ]:
# Let's display some various attributes of the tensor: 
print("Datatype of every element:", rank_2_tensor.dtype)
print("Number of dimensions (rank):", rank_2_tensor.ndim)
print("Shape of tensor:", rank_2_tensor.shape)
print("Elements along the 0-axis:", rank_2_tensor.shape[0])
print("Elements along the last axis:", rank_2_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_2_tensor))
print("Total number of elements in our tensor:", tf.size(rank_2_tensor).numpy())

In [ ]:
# Get the last item of each row of our rank 2 tensor: 
rank_2_tensor[:,-1] 

In [ ]:
# Add in extra dimension to our rank 2 tensor: 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Let's display some various attributes of our rank 3 tensor:
print("Datatype of every element:", rank_3_tensor.dtype) 
print("Number of dimensions (rank):", rank_3_tensor.ndim) 
print("Shape of tensor:", rank_3_tensor.shape) 
print("Elements along the 0-axis:", rank_3_tensor.shape[0]) 
print("Elements along the last axis:", rank_3_tensor.shape[-1]) 
print("Total number of elements in our tensor:", tf.size(rank_3_tensor)) 
print("Total number of elements in our tensor:", tf.size(rank_3_tensor).numpy()) 

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis


### Manipulatig tensors (tensor operations)

## Basic operations 

* Addition : "+"
* Substraction : "-"
* Multiplication : "x"
* Division : "/"

In [ ]:
# Let's create a dummy tensor to perform some basic operations on it:
dummy_tensor = tf.constant([[1,2], [3,4], [5,6]])
dummy_tensor

In [ ]:
# Let's add values to our dummy tensor using the addition operator:
dummy_tensor + 10

In [ ]:
# Let's subsracte some values from our dummy tensor using the substraction operator:
dummy_tensor - 5

In [ ]:
# Let's multiply our dummy tensor with a scalar using the multiplication operator: 
dummy_tensor * 4

In [ ]:
# etc.....

**Matrix multiplication**

In Machine Learning matrix multiplication is one of the most common tensor operations. 

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them: 

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions 

In [ ]:
# Matrix multiplication in tensorflow:
print(dummy_tensor) 
# Let's create two new dummy tensors; 
# Fist one:
dummy_tensor1 = tf.constant([[1, 2], 
                             [3, 4]])
# Second one: 
dummy_tensor2 = tf.constant([[5, 6],
                             [7, 8]])


In [ ]:
# Let's do some tensor multiplication using tf.matmul()
tf.matmul(dummy_tensor1, dummy_tensor2)

In [ ]:
# Matrix Multiplication using Python operator (at) "@"
# Let's try it:
dummy_tensor1 @ dummy_tensor2

In [ ]:
# A little exerice: 
# Let's create two new tensors: 
# First one [3x3]: 
tensor_1 = tf.constant([[1, 2, 5],[7, 2, 1],[3, 3, 3]])
# Second one [3x2]:
tensor_2 = tf.constant([[3, 5],[6, 7],[1, 8]])
# Let's do some tensor multiplication: 
tf.matmul(tensor_1,tensor_2)

In [ ]:
# Let's try the multiplication using the Pyton operator "@"
tensor_1 @ tensor_2

In [ ]:
print("Display the tensor shapes:", tensor_1.shape, tensor_2.shape)

In [ ]:
# Let's create another (3x2) tensors:
# First one: 
X = tf.constant([[1, 2],[3, 4],[5, 6]])
# Second one: 
Y = tf.constant([[7, 8],[9, 10],[11, 12]])
X, Y

In [ ]:
# Let's try to multiply tensors of the shame shape using the python operator "@"
X @ Y

In [ ]:
# Let's now to multiply them using the tf.matmul() method:
tf.matmul(X,Y)

📖**Resource:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html  

In [ ]:
# Let's change the shape of Y:  
print("The Shape of Y before reshaping it:", Y.shape)
print("The Shape of Y after reshaping it:", tf.reshape(Y, shape=(2,3)))

In [ ]:
# Now let's do some multiplication again: 
# Try to multiply X by Y: 
# Matrix multiplication using the Python operator "@":
X @ tf.reshape(Y,shape=(2,3))

In [ ]:
# Using the tensorflow method tf.matmul()
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

In [ ]:
# Let's reverse what we hhave just done 
# Reverse X instead of Y, and dome some matrix/tensor multiplication
# Matrix multiplication using the Python operator "@"
tf.reshape(X,shape=(2,3)) @ Y

In [ ]:
# Tensor Multiplication using the tensorflow tf.matmul() method:

tf.matmul(tf.reshape(X,shape=(2,3)),Y)

In [ ]:
# Let's try to do the same thing with transpose: 
# But first let's have a quick look at the difference between the two methods tf.transpose() and tf.reshape():
X, tf.transpose(X), tf.reshape(X,shape=(2,3))

In [ ]:
# Let's try some matrix multiplication using the method tf.transpose() rather than using the method tf.reshape():
# Matrix Multiplication using the Python operator "@".
tf.transpose(X) @ Y

In [ ]:
X @ tf.transpose(Y)

In [ ]:
# Matrix multiplication using the tf.matmul() method:
tf.matmul(X,tf.transpose(Y))

In [ ]:
tf.matmul(tf.transpose(X),Y)

**The dot product** 

Matrix multiplication is also reffered to as the dot product. 

You can peform matrix multiplication using: 
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
print(X,Y)

In [ ]:
# Peform the dot product on X and Y (requires X or Y to be transposed):
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
# Let's try with the method tf.reshape(,shape=())
tf.tensordot(tf.reshape(X,shape=(2,3)), Y, axes=1)

In [ ]:
# Let's try matrix multiplication by transposing and reshaping Y:
# Transposing Y:
tf.tensordot(X, tf.transpose(Y), axes=1)

In [ ]:
# Reshaping Y: 
tf.tensordot(X, tf.reshape(Y,shape=(2,3)), axes=1)

In [ ]:
# Check the Values of X, reshaped X and transposed X: 
print("Normal X:")
print(X, "\n")
print("Reshaped X:")
print(tf.reshape(X,shape=(2,3)), "\n") # "\n" is for a new line
print("Transposed X:")
print(tf.transpose(X))

In [ ]:
# Let's Check the values of Y, reshaped Y and transposed Y: 
print("Normal Y:")
print(Y, "\n")
print("Reshaped Y:")
print(tf.reshape(Y,shape=(2,3)), "\n") # "\n" is for newline
print("Transposed Y:")
print(tf.transpose(Y))

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose
rather than reshape one of the tensors to satisfy the matrix multiplication. 

### Changing the datatype of a tensor:

In [ ]:
# Create a new Tensor with a default datatype (float32):
dummy_tensor1 = tf.constant([[1.1, 2.0], [5.1, 9.5]])
# Display the datatype of our first dummmy tensor: 
print("The datatype of the dummy_tensor1 is:", dummy_tensor1.dtype)

In [ ]:
# Let's create a second dummy tensor and display it's datatype:
dummy_tensor2 = tf.constant([[9, 10], [7, 2]])
print("The datatype of the dummy_tensor2 is:", dummy_tensor2.dtype)

In [ ]:
# Change from float32 to float16 (this is called reduced precision)
dummy_tensor1 = tf.cast(dummy_tensor1, dtype=tf.float16)
print("The datatype of the dummy_tensor1 is: ", dummy_tensor1.dtype)

In [ ]:
# Change the dummy_tensor2 from int32 to int16 
dummy_tensor2 = tf.cast(dummy_tensor2, dtype=tf.int16)
print("The datatype of the dummy_tensor2 is:", dummy_tensor2.dtype)

## Aggregating Tensors

Aggeragating tensors = condensing them form multiple values down to a smaller amout of values.



In [ ]:
# Let's create a new tensor and get it's absolute value: 
dummy_tensor3 = tf.constant([1, 2])
abs_val = tf.abs(dummy_tensor3)
print("The absolute value of this tensor is:", abs_val)

In [ ]:
#: 
dummy_tensor4 = tf.constant([[-10, -8], [2, -1]])
abs_val1 = tf.abs(dummy_tensor4)
print("The absolute value of this tensor is:", abs_val1)

Let's go through the following form of aggregation: 

* Get the maximum 
* Get the minimum 
* Get the mean of a tensor 
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100  
E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
# Let's display some characteristics of our tensor: 
print("The size of the tensor is: ", tf.size(E))
print("The shape of the tensor is: ", E.shape)
print("The datatype of the tensor is: ", E.dtype)

In [ ]:
# Let's Create a second random tensor with value between 0 and 50 
F = tf.constant(np.random.randint(0, 50, size=40))
F

In [ ]:
# Let's display some characteristics of the tensor:
print("The size of the tensor is: ", tf.size(F))
print("The shape of the tensor is:", F.shape)
print("The datatype of the tensor is:", F.dtype)

In [ ]:
# Let's find the maximum values in the tensors; 
max_E = tf.reduce_max(E)
max_F = tf.reduce_max(F)
print("The maximum value in E is:", max_E)
print("The maximum value in F is:", max_F)

In [ ]:
# Let's now find the minimum values in the tensors:
min_E = tf.reduce_min(E)
min_F = tf.reduce_min(F)
print("The minimum value in E is:", min_E)
print("The minimum value in F is:", min_F)

In [ ]:
# Let's get the mean of our tensor:
mean_E = tf.reduce_mean(E)
mean_F = tf.reduce_mean(F)
print("The mean in E is:", mean_E)
print("The mean in F is:", mean_F)

In [ ]:
# Let's get the sum of all the values of the tensors:
sum_E = tf.reduce_sum(E)
sum_F = tf.reduce_sum(F)
print("The Sum of E is:", sum_E)
print("The Sum of S is:", sum_F)

 ⚒**Exericise**: With what we have just learned, find the variance and standard deviation of our E tensor using TensorFlow methods.

In [61]:
#Let's import the necessay packages first: 
import tensorflow as tf
import numpy as np
# Create a random tensor with values between 0 and 100  
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89,  4, 60, 86, 91, 63, 24, 60, 24, 14, 53, 26, 58, 53, 37,  0, 66,
       64, 41, 77, 16, 11, 19,  6, 91, 99, 47, 20, 91, 49, 16, 83,  3, 53,
       63, 13, 31, 67, 39, 65, 99, 18, 18, 26, 99, 69, 26, 71,  0, 62])>

In [62]:
# Find the variance of our tensor
tf.reduce_var(E) # this won't work

AttributeError: ignored

In [63]:
tf.reduce_variance(E) # this won't work

AttributeError: ignored

In [64]:
# To find the variance of our tensor, we need access to tensor_probability 
import tensorflow_probability as tfp
tfp.stats.reduce_variance(E)

AttributeError: ignored

In [65]:
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=890>

In [66]:
# Find the standard deviation: 
tf.reduce_std(E) # this won't work


AttributeError: ignored

In [67]:
# Find the standard deviation: 
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.83957>

### Find the positional maximum and minimum

In [68]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [69]:
# Find the positional maximum:
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [72]:
# Index on our largest value position:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [71]:
# Find the max value of F:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [73]:
# Check for equality just to be safe:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [74]:
# Find the positional minimum: 
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [75]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [77]:
# Let's create a random tensor to find it's positional minimum and maximum: 
tf.random.set_seed(42)
dummy_tensor3 = tf.random.uniform(shape=[40])
dummy_tensor3

<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
      dtype=float32)>

In [79]:
# Find the positional maximum: 
tf.argmax(dummy_tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [80]:
# Index on our largest value position: 
dummy_tensor3[tf.argmax(dummy_tensor3)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9485276>

In [81]:
# Find the maximum value of dummy_tensor3:
tf.reduce_max(dummy_tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9485276>

In [82]:
# Check for equality:
dummy_tensor3[tf.argmax(dummy_tensor3)] == tf.reduce_max(dummy_tensor3)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [83]:
# Let's find the positional minimum: 
tf.argmin(dummy_tensor3)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [84]:
# Index on our smallest value position:
dummy_tensor3[tf.argmin(dummy_tensor3)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [85]:
# Find the min value of dummy_tensor3:
tf.reduce_min(dummy_tensor3)


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [86]:
# Check for equality: 
dummy_tensor3[tf.argmin(dummy_tensor3)] == tf.reduce_min(dummy_tensor3)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [103]:
# Let's create a tensor to get started: 
tf.random.set_seed(42)
tensor3 = tf.constant(tf.random.uniform(shape=[30]), shape=(1,1,1,1,30))
tensor3

<tf.Tensor: shape=(1, 1, 1, 1, 30), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173]]]]],
      dtype=float32)>

In [104]:
# Display the shape of the tensor: 
print("Shape is:",tensor3.shape)

Shape is: (1, 1, 1, 1, 30)


In [105]:
# Let's squeeze our tensor (which means let's remove all single dimensions): 
tensor_squeezed = tf.squeeze(tensor3)
# Display the shape of the squeezed tensor:
print("The shape of squeezed tensor is:",tensor_squeezed)

The shape of squeezed tensor is: tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173], shape=(30,), dtype=float32)


###One hot encoding tensors

In [107]:
# Let's create a list of indices: 
some_list=[0, 1, 2, 3] # could be red, green, blue, purpble
# One hot encode our lists of indices: 
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [108]:
# Specify custom values for one hot encoding: 
tf.one_hot(some_list, depth=4, on_value="My Name is EL Mehdi", off_value="I like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'My Name is EL Mehdi', b'I like to dance', b'I like to dance',
        b'I like to dance'],
       [b'I like to dance', b'My Name is EL Mehdi', b'I like to dance',
        b'I like to dance'],
       [b'I like to dance', b'I like to dance', b'My Name is EL Mehdi',
        b'I like to dance'],
       [b'I like to dance', b'I like to dance', b'I like to dance',
        b'My Name is EL Mehdi']], dtype=object)>

In [114]:
# Let's create a second list of indices: 
random_list = [0, 1, 2]
# One hot encode our lists of indices: 
 tf.one_hot(random_list, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [115]:
# Specify custom values for one hot encoding: 
tf.one_hot(random_list, depth=4, on_value="Deep", off_value="Learning")

<tf.Tensor: shape=(3, 4), dtype=string, numpy=
array([[b'Deep', b'Learning', b'Learning', b'Learning'],
       [b'Learning', b'Deep', b'Learning', b'Learning'],
       [b'Learning', b'Learning', b'Deep', b'Learning']], dtype=object)>

###More tensor math operations

####Squaring, log, square root

In [117]:
# Let's create a new tensor 
dummy_tensor4 = tf.range(1,20)
dummy_tensor4

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [119]:
# Squate it: 
tf.square(dummy_tensor4)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)>

In [120]:
# Find the squareroot: 
tf.sqrt(dummy_tensor4)

InvalidArgumentError: ignored

In [121]:
# Let's give it another try: 
tf.sqrt(tf.cast(dummy_tensor4, dtype=tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 2.9999998 , 3.1622777 ,
       3.3166244 , 3.4641016 , 3.6055508 , 3.7416573 , 3.8729832 ,
       3.9999998 , 4.1231055 , 4.2426405 , 4.358899  ], dtype=float32)>

In [122]:
# Find the log:
tf.math.log(dummy_tensor4)

InvalidArgumentError: ignored

In [123]:
# Let's give it another try: 
tf.math.log(tf.cast(dummy_tensor4, dtype=tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

### TensorFlow and NumPy's compatibility

TensorFlow interacts beautifully with NumPy arrays

In [124]:
# Let's Create a tensor directly from a NumPy array: 
J = tf.constant(np.array([3., 7., 10.]))
J 

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [126]:
# Convert our tensor back to a NumPy array:
np.array(J)
# Display the type:
print("Type is:", type(np.array(J)))

Type is: <class 'numpy.ndarray'>


In [ ]:
# Let's convert tensor J to a NumPy array: 
J.numpy(), type(J.numpy())

In [129]:
# The default types of each are slightly different: 
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

In [130]:
# Let's Check the datatype of each: 
print("The Datatype of the NumPy array is:",numpy_J.dtype)
print("The Datatype of the tensor is:",tensor_J.dtype)

The Datatype of the NumPy array is: <dtype: 'float64'>
The Datatype of the tensor is: <dtype: 'float32'>


🔐**Note:** One of the main differences between a TensorFlow tensor and a NumPy array is that TensorFlow tensor can be run on a GPU or a TPU 
(for a faster numerical processing)

###Finding access to GPUs

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
tf.config.list_physical_devices("CPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [5]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [7]:
!nvidia-smi

Mon Apr 18 12:15:47 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P8    32W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔐**Note:** if you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible